import { IMember } from '../../schema/memberSchema';

export const MockMemberList: IMember[] = [
  {
    title: 'Mr',
    firstName: 'John',
    lastName: 'Smith',
    address: {
      addressLine1: '',
      addressLine2: '',
      suburb: '',
      state: '',
      postcode: '',
      formattedAddress: '256 George St Sydney NSW 2000',
    },
    phone: '0405202222',
    email: 'john.smith@google.com',
    dob: '20/08/2000',
    memberType: '',
    status: 'A',
    membershipStatedFrom: '04/05/2000',
    expiryDate: '12/05/2025',
  },
  {
    title: 'Mr',
    firstName: 'John',
    lastName: 'Smith',
    address: {
      addressLine1: '',
      addressLine2: '',
      suburb: '',
      state: '',
      postcode: '',
      formattedAddress: '256 George St Sydney NSW 2000',
    },
    phone: '0405202222',
    email: 'john.smith@google.com',
    dob: '20/08/2000',
    memberType: '',
    status: 'A',
    membershipStatedFrom: '04/05/2000',
    expiryDate: '12/05/2025',
  },
  {
    title: 'Mr',
    firstName: 'John',
    lastName: 'Smith',
    address: {
      addressLine1: '',
      addressLine2: '',
      suburb: '',
      state: '',
      postcode: '',
      formattedAddress: '256 George St Sydney NSW 2000',
    },
    phone: '0405202222',
    email: 'john.smith@google.com',
    dob: '20/08/2000',
    memberType: '',
    status: 'A',
    membershipStatedFrom: '04/05/2000',
    expiryDate: '12/05/2025',
  },
  {
    title: 'Mr',
    firstName: 'John',
    lastName: 'Smith',
    address: {
      addressLine1: '',
      addressLine2: '',
      suburb: '',
      state: '',
      postcode: '',
      formattedAddress: '256 George St Sydney NSW 2000',
    },
    phone: '0405202222',
    email: 'john.smith@google.com',
    dob: '20/08/2000',
    memberType: '',
    status: 'A',
    membershipStatedFrom: '04/05/2000',
    expiryDate: '12/05/2025',
  },
  {
    title: 'Mr',
    firstName: 'John',
    lastName: 'Smith',
    address: {
      addressLine1: '',
      addressLine2: '',
      suburb: '',
      state: '',
      postcode: '',
      formattedAddress: '256 George St Sydney NSW 2000',
    },
    phone: '0405202222',
    email: 'john.smith@google.com',
    dob: '20/08/2000',
    memberType: '',
    status: 'A',
    membershipStatedFrom: '04/05/2000',
    expiryDate: '12/05/2025',
  },
  {
    title: 'Mr',
    firstName: 'John',
    lastName: 'Smith',
    address: {
      addressLine1: '',
      addressLine2: '',
      suburb: '',
      state: '',
      postcode: '',
      formattedAddress: '256 George St Sydney NSW 2000',
    },
    phone: '0405202222',
    email: 'john.smith@google.com',
    dob: '20/08/2000',
    memberType: '',
    status: 'A',
    membershipStatedFrom: '04/05/2000',
    expiryDate: '12/05/2025',
  },
  {
    title: 'Mr',
    firstName: 'John',
    lastName: 'Smith',
    address: {
      addressLine1: '',
      addressLine2: '',
      suburb: '',
      state: '',
      postcode: '',
      formattedAddress: '256 George St Sydney NSW 2000',
    },
    phone: '0405202222',
    email: 'john.smith@google.com',
    dob: '20/08/2000',
    memberType: '',
    status: 'A',
    membershipStatedFrom: '04/05/2000',
    expiryDate: '12/05/2025',
  },
  {
    title: 'Mr',
    firstName: 'John',
    lastName: 'Smith',
    address: {
      addressLine1: '',
      addressLine2: '',
      suburb: '',
      state: '',
      postcode: '',
      formattedAddress: '256 George St Sydney NSW 2000',
    },
    phone: '0405202222',
    email: 'john.smith@google.com',
    dob: '20/08/2000',
    memberType: '',
    status: 'A',
    membershipStatedFrom: '04/05/2000',
    expiryDate: '12/05/2025',
  },
  {
    title: 'Mr',
    firstName: 'John',
    lastName: 'Smith',
    address: {
      addressLine1: '',
      addressLine2: '',
      suburb: '',
      state: '',
      postcode: '',
      formattedAddress: '256 George St Sydney NSW 2000',
    },
    phone: '0405202222',
    email: 'john.smith@google.com',
    dob: '20/08/2000',
    memberType: '',
    status: 'A',
    membershipStatedFrom: '04/05/2000',
    expiryDate: '12/05/2025',
  },
  {
    title: 'Mr',
    firstName: 'John',
    lastName: 'Smith',
    address: {
      addressLine1: '',
      addressLine2: '',
      suburb: '',
      state: '',
      postcode: '',
      formattedAddress: '256 George St Sydney NSW 2000',
    },
    phone: '0405202222',
    email: 'john.smith@google.com',
    dob: '20/08/2000',
    memberType: '',
    status: 'A',
    membershipStatedFrom: '04/05/2000',
    expiryDate: '12/05/2025',
  },
  {
    title: 'Mr',
    firstName: 'John',
    lastName: 'Smith',
    address: {
      addressLine1: '',
      addressLine2: '',
      suburb: '',
      state: '',
      postcode: '',
      formattedAddress: '256 George St Sydney NSW 2000',
    },
    phone: '0405202222',
    email: 'john.smith@google.com',
    dob: '20/08/2000',
    memberType: '',
    status: 'A',
    membershipStatedFrom: '04/05/2000',
    expiryDate: '12/05/2025',
  },
  {
    title: 'Mr',
    firstName: 'John',
    lastName: 'Smith',
    address: {
      addressLine1: '',
      addressLine2: '',
      suburb: '',
      state: '',
      postcode: '',
      formattedAddress: '256 George St Sydney NSW 2000',
    },
    phone: '0405202222',
    email: 'john.smith@google.com',
    dob: '20/08/2000',
    memberType: '',
    status: 'A',
    membershipStatedFrom: '04/05/2000',
    expiryDate: '12/05/2025',
  },
];
